version: '3.8'

services:
  auth:
    image: auth:latest
    container_name: auth
    environment:
      - eureka.client.serviceUrl.defaultZone = http://172.17.0.1:8761/eureka/
    ports:
      - 9100:9100
    networks:
      - icommercenetwork

networks:
  icommercenetwork:
    driver: bridge
