version: '3.3'

services:
  eureka:
    image: eureka:3
    container_name: eureka
    ports:
      - 8761:8761
    networks:
      - icommercenetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  icommercenetwork:
    driver: bridge
