version: '3.8'

services:
  spring_eureka_server:
    image: spring-eureka-server
    container_name: spring_eureka_server
    ports:
      - 8761:8761
    networks:
      - huongdanjava
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  huongdanjava:
    driver: bridge
